# Generated by Django 3.0.3 on 2020-02-11 11:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название страницы')),
                ('url', models.SlugField(max_length=160, unique=True, verbose_name='Символьный код')),
                ('preview_text', models.TextField(blank=True, null=True, verbose_name='Описание анонса')),
                ('detail_text', models.TextField(blank=True, null=True, verbose_name='Детальное описание')),
                ('img_preview', models.ImageField(blank=True, null=True, upload_to='page/page_img_preview/', verbose_name='Картинка для анонса')),
                ('img_detail', models.ImageField(blank=True, null=True, upload_to='page/page_img_detail/', verbose_name='Детальная картинка')),
                ('img_og', models.ImageField(blank=True, null=True, upload_to='page/page_img_og/', verbose_name='Картинка для Open graph')),
                ('youtube_link', models.CharField(blank=True, max_length=160, null=True, verbose_name='Ссылка на видео YouTube')),
                ('head_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок окна браузера')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta Description')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок h1 страницы)')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('date_begin', models.DateField(default=datetime.date.today, verbose_name='Дата начала активности')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания активности')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PageImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название картинки')),
                ('img', models.ImageField(upload_to='page/page_img/', verbose_name='Изображение')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsoft_cms.Page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
