name: CI

on:
  push:
    branches:
    - dev

jobs:
  build:
    name: yarn build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: yarn install
    - run: yarn build
    - name: Add and Commit changes
      run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -A
          git commit -m 'Production build'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: frontend

  deploy:
    name: ssh deploy and collectstatic
    runs-on: [ubuntu-latest]
    needs: [build]

    steps:
      - name: Collectstatic
        uses: appleboy/ssh-action@v0.0.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/crm.netaxi29.ru/
            git pull
            git merge origin/frontend
            cd public_html/
            source myenv/bin/activate
            rm -r crm/assets
            python crm/manage.py collectstatic --noinput
            cd ~/crm.netaxi29.ru/
            git config --local user.email 'action@github.com'
            git config --local user.name 'GitHub Action'
            git add -A
            git commit -m 'Collectstatic'
            git push
      # - name: Final pull
      #   uses: appleboy/ssh-action@v0.0.6
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       cd ~/crm.netaxi29.ru/
      #       git pull
